## Basic configs for dotfiles installation.

# source_file is based on cwd (current working directory)
# destination_file is based on user's home dir.
dotfiles:
- source_file: _vimrc
  destination_file: ".vimrc"
  action_type: symlink

- source_file: _bashrc
  destination_file: ".bashrc"
  action_type: symlink

# Suggestions for next step. A list of config files are suggested, they are
# per-machine configs (do not commit them back to the GitHub repo)
#
# destination_files are based on user's home dir.
suggestions:
- destination_file: .vimrc.local
  description: Put your machine specific VIM settings here
- destination_file: .bash_aliases
  description: Put your machine specific Bash settings here

